CREATE TABLE tbl_archivos (
    codigo_archivo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    estado         NUMBER NOT NULL,
    usuario        NUMBER NOT NULL,
    carpeta        NUMBER,
    tipo_archivo   NUMBER NOT NULL,
    nombre_archivo VARCHAR2(50) NOT NULL,
    descripcion    VARCHAR2(200),
    fecha_subido   DATE NOT NULL,
    PRIMARY KEY(codigo_archivo)
);

CREATE TABLE tbl_carpetas (
    codigo_carpeta NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    estado         NUMBER NOT NULL,
    carpeta_padre  NUMBER,
    nombre_carpeta VARCHAR2(50) NOT NULL,
    PRIMARY KEY(codigo_carpeta)
);

CREATE TABLE tbl_comentarios (
    codigo_comentario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    codigo_archivo    NUMBER NOT NULL,
    usuario           NUMBER NOT NULL,
    comentario        VARCHAR2(50) NOT NULL,
    fecha_comentario  DATE NOT NULL,
    PRIMARY KEY(codigo_comentario)
);
 
CREATE TABLE tbl_compartidos (
    archivo             NUMBER NOT NULL,
    usuario_propietario NUMBER,
    usuario_compartido  NUMBER NOT NULL,
    PRIMARY KEY(archivo)
);

CREATE TABLE tbl_compartidos_x_permisos (
    archivo NUMBER NOT NULL,
    permiso NUMBER NOT NULL
);

CREATE TABLE tbl_computadoras (
    codigo_computadora NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    usuario            NUMBER NOT NULL,
    nombre_pc          VARCHAR2(50) NOT NULL,
    PRIMARY KEY(codigo_computadora)
);

CREATE TABLE tbl_datos_privacidad (
    codigo_datos_priv NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    verificacion      VARCHAR2(50) NOT NULL,
    PRIMARY KEY(codigo_datos_priv)
);

CREATE TABLE tbl_datos_x_historial (
    datos_priv NUMBER NOT NULL,
    historial  NUMBER NOT NULL
);

CREATE TABLE tbl_direcciones (
    codigo_direccion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_direccion   NUMBER NOT NULL,
    PRIMARY KEY(codigo_direccion)
);

CREATE TABLE tbl_estados (
    codigo_estado NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    estado        VARCHAR2(20) NOT NULL,
    PRIMARY KEY(codigo_estado)
);

CREATE TABLE tbl_etiquetas (
    codigo_etiqueta NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    codigo_usuario  NUMBER NOT NULL,
    etiqueta        VARCHAR2(50) NOT NULL,
    color           VARCHAR2(50) NOT NULL,
    PRIMARY KEY(codigo_etiqueta)
);

CREATE TABLE tbl_grupos (
    codigo_grupo   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre         VARCHAR2(50) NOT NULL,
    fecha_creacion DATE NOT NULL,
    PRIMARY KEY(codigo_grupo)
);

CREATE TABLE tbl_grupos_x_usuarios (
    codigo_administrador NUMBER NOT NULL,
    codigo_grupo         NUMBER NOT NULL,
    codigo_archivo       NUMBER NOT NULL,
    codigo_usuario       NUMBER NOT NULL,
    usuario_dueño_arc    NUMBER NOT NULL
);

ALTER TABLE tbl_grupos_x_usuarios 
ADD CONSTRAINT tbl_grupos_x_usuarios_pk 
PRIMARY KEY ( codigo_administrador, codigo_grupo );

CREATE TABLE tbl_historial_cambios (
    codigo_cambio  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    codigo_archivo NUMBER NOT NULL,
    tbl_archivos   NUMBER NOT NULL,
    descripcion    VARCHAR2(50) NOT NULL,
    fecha_cambio   DATE NOT NULL,
    PRIMARY KEY(codigo_cambio)
);

CREATE TABLE tbl_historiales (
    codigo_historial NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    historial        VARCHAR2(100) NOT NULL,
    estado           VARCHAR2(5) NOT NULL,
    PRIMARY KEY(codigo_historial)
);

CREATE TABLE tbl_metodos_pago (
    codigo_metodo_pago NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_metodo_pago   VARCHAR2(20) NOT NULL,
    PRIMARY KEY(codigo_metodo_pago)
);

CREATE TABLE tbl_notificaciones (
    codigo_notificacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipos_notif         NUMBER NOT NULL,
    descripcion         VARCHAR2(200) NOT NULL,
    PRIMARY KEY(codigo_notificacion)
);

CREATE TABLE tbl_notificaciones_x_usr (
    codigo_usuario      NUMBER NOT NULL,
    codigo_notificacion NUMBER NOT NULL
);

ALTER TABLE tbl_notificaciones_x_usr 
ADD CONSTRAINT tbl_notificaciones_x_usr_pk 
PRIMARY KEY ( codigo_usuario, codigo_notificacion );

CREATE TABLE tbl_ofertas (
    codigo_oferta NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    descuento     NUMBER NOT NULL,
    duracion      DATE NOT NULL,
    PRIMARY KEY(codigo_oferta)
);

CREATE TABLE tbl_permisos (
    codigo_permiso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_permiso   VARCHAR2(10) NOT NULL,
    PRIMARY KEY(codigo_permiso)
);

CREATE TABLE tbl_planes (
    codigo_plan    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    oferta         NUMBER,
    nombre_plan    VARCHAR2(50) NOT NULL,
    duracion       DATE NOT NULL,
    descripcion    VARCHAR2(200) NOT NULL,
    precio         NUMBER NOT NULL,
    almacenamiento NUMBER NOT NULL,
    PRIMARY KEY(codigo_plan)
);

CREATE TABLE tbl_preferencias (
    codigo_preferencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_preferencia   NUMBER NOT NULL,
    PRIMARY KEY(codigo_preferencia)
);

CREATE TABLE tbl_registros_actividades (
    codigo_regi_act NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    codigo_usuario  NUMBER NOT NULL,
    tipo_actividad  VARCHAR2(50) NOT NULL,
    fecha_actividad DATE NOT NULL,
    PRIMARY KEY(codigo_regi_act)
);

CREATE TABLE tbl_tarjetas (
    codigo_tarjeta    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    metodo_pago       NUMBER NOT NULL,
    numero_tarjeta    VARCHAR2(20) NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    codigo_seguridad  NUMBER NOT NULL,
    codigo_postal     VARCHAR2(10) NOT NULL,
    PRIMARY KEY(codigo_tarjeta)
);

CREATE TABLE tbl_tipos_archivo (
    codigo_tipo_archivo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_archivo        VARCHAR2(50) NOT NULL,
    peso                NUMBER NOT NULL,
    PRIMARY KEY(codigo_tipo_archivo)
);

CREATE TABLE tbl_tipos_notificaciones(
    codigo_tipos_notif NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_notificacion  VARCHAR2(50) NOT NULL,
    PRIMARY KEY(codigo_tipos_notif)
);

CREATE TABLE tbl_usuarios (
    codigo_usuario   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    preferencia      NUMBER NOT NULL,
    tarjeta          NUMBER NOT NULL,
    datos_priv       NUMBER NOT NULL,
    plan             NUMBER NOT NULL,
    direccion        NUMBER NOT NULL,
    fotoperfil       BLOB,
    nombre           VARCHAR2(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    genero           VARCHAR2(10),
    correo           VARCHAR2(90) NOT NULL,
    clave            VARCHAR2(50) NOT NULL,
    correo_adicional VARCHAR2(90),
    telefono         VARCHAR2(100),
    formacion        VARCHAR2(50),
    trabajo          VARCHAR2(50),
    PRIMARY KEY(codigo_usuario)
);

CREATE TABLE tbl_versiones_archivo (
    codigo_version      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    codigo_archivo      NUMBER NOT NULL,
    usuario             NUMBER NOT NULL,
    fecha_actualizacion DATE NOT NULL,
    PRIMARY KEY(codigo_version)
);

CREATE TABLE tbl_tipo_preferencia (
    codigo_tipo_preferencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_preferencia        VARCHAR2(200) NOT NULL,
    PRIMARY KEY(codigo_tipo_preferencia)
);

CREATE TABLE tbl_tipos_direccion (
    codigo_tipo_direccion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_direccion        VARCHAR2(50) NOT NULL,
    PRIMARY KEY(codigo_tipo_direccion)
);

ALTER TABLE tbl_archivos
ADD CONSTRAINT tbl_archivos_tbl_carpetas_fk 
FOREIGN KEY ( carpeta ) REFERENCES tbl_carpetas ( codigo_carpeta );

ALTER TABLE tbl_archivos
ADD CONSTRAINT tbl_archivos_tbl_estados_fk 
FOREIGN KEY ( estado ) REFERENCES tbl_estados ( codigo_estado );

ALTER TABLE tbl_archivos
ADD CONSTRAINT tbl_archivos_tbl_tipos_archivo_fk 
FOREIGN KEY ( tipo_archivo ) REFERENCES tbl_tipos_archivo ( codigo_tipo_archivo );

ALTER TABLE tbl_archivos
ADD CONSTRAINT tbl_archivos_tbl_usuarios_fk 
FOREIGN KEY ( usuario ) REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_carpetas
ADD CONSTRAINT tbl_carpetas_tbl_carpetas_fk 
FOREIGN KEY ( carpeta_padre ) REFERENCES tbl_carpetas ( codigo_carpeta );

ALTER TABLE tbl_carpetas
ADD CONSTRAINT tbl_carpetas_tbl_estados_fk
FOREIGN KEY ( estado ) REFERENCES tbl_estados ( codigo_estado );

ALTER TABLE tbl_comentarios
ADD CONSTRAINT tbl_comentarios_tbl_archivos_fk 
FOREIGN KEY ( codigo_archivo ) REFERENCES tbl_archivos ( codigo_archivo );

ALTER TABLE tbl_compartidos
ADD CONSTRAINT tbl_compartidos_tbl_archivos_fk 
FOREIGN KEY ( usuario_propietario ) REFERENCES tbl_archivos ( codigo_archivo );

ALTER TABLE tbl_compartidos
ADD CONSTRAINT tbl_compartidos_tbl_usuarios_fk
FOREIGN KEY ( usuario_compartido ) REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_compartidos_x_permisos
ADD CONSTRAINT tbl_compartidos_x_permisos_tbl_compartidos_fk 
FOREIGN KEY ( archivo ) REFERENCES tbl_compartidos ( archivo );

ALTER TABLE tbl_compartidos_x_permisos
ADD CONSTRAINT tbl_compartidos_x_permisos_tbl_permisos_fk 
FOREIGN KEY ( permiso ) REFERENCES tbl_permisos ( codigo_permiso );

ALTER TABLE tbl_computadoras
ADD CONSTRAINT tbl_computadoras_tbl_usuarios_fk 
FOREIGN KEY ( usuario ) REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_datos_x_historial
ADD CONSTRAINT tbl_datos_x_historial_tbl_datos_privacidad_fk 
FOREIGN KEY ( datos_priv ) REFERENCES tbl_datos_privacidad ( codigo_datos_priv );

ALTER TABLE tbl_datos_x_historial
ADD CONSTRAINT tbl_datos_x_historial_tbl_historiales_fk 
FOREIGN KEY ( historial ) REFERENCES tbl_historiales ( codigo_historial );

ALTER TABLE tbl_direcciones
ADD CONSTRAINT tbl_direcciones_tipos_direccion_fk 
FOREIGN KEY ( tipo_direccion ) REFERENCES tbl_tipos_direccion ( codigo_tipo_direccion );

ALTER TABLE tbl_etiquetas
ADD CONSTRAINT tbl_etiquetas_tbl_usuarios_fk 
FOREIGN KEY ( codigo_usuario ) REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_grupos_x_usuarios
ADD CONSTRAINT tbl_grupos_x_usuarios_tbl_archivos_fk 
FOREIGN KEY ( usuario_dueño_arc ) REFERENCES tbl_archivos ( codigo_archivo );

ALTER TABLE tbl_grupos_x_usuarios
ADD CONSTRAINT tbl_grupos_x_usuarios_tbl_grupos_fk 
FOREIGN KEY ( codigo_grupo ) REFERENCES tbl_grupos ( codigo_grupo );

ALTER TABLE tbl_grupos_x_usuarios
ADD CONSTRAINT tbl_grupos_x_usuarios_tbl_usuarios_fk 
FOREIGN KEY ( codigo_usuario ) REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_grupos_x_usuarios
ADD CONSTRAINT tbl_grupos_x_usuarios_tbl_usuarios_fk2
FOREIGN KEY ( codigo_administrador ) REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_historial_cambios
ADD CONSTRAINT tbl_historial_cambios_tbl_archivos_fk 
FOREIGN KEY ( codigo_archivo ) REFERENCES tbl_archivos ( codigo_archivo );

ALTER TABLE tbl_notificaciones
ADD CONSTRAINT tbl_notificaciones_tbl_tipos_notificacion_fk 
FOREIGN KEY ( tipos_notif ) REFERENCES tbl_tipos_notificaciones ( codigo_tipos_notif );

ALTER TABLE tbl_notificaciones_x_usr
ADD CONSTRAINT tbl_notificaciones_x_usr_tbl_notificaciones_fk 
FOREIGN KEY ( codigo_notificacion ) REFERENCES tbl_notificaciones ( codigo_notificacion );

ALTER TABLE tbl_notificaciones_x_usr
ADD CONSTRAINT tbl_notificaciones_x_usr_tbl_usuarios_fk 
FOREIGN KEY ( codigo_usuario ) REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_planes
ADD CONSTRAINT tbl_planes_tbl_ofertas_fk 
FOREIGN KEY ( oferta ) REFERENCES tbl_ofertas ( codigo_oferta );

ALTER TABLE tbl_preferencias
ADD CONSTRAINT tbl_preferencias_tipo_preferencia_fk 
FOREIGN KEY ( tipo_preferencia ) REFERENCES tbl_tipo_preferencia ( codigo_tipo_preferencia );

ALTER TABLE tbl_registros_actividades
ADD CONSTRAINT tbl_registros_actividades_tbl_usuarios_fk 
FOREIGN KEY ( codigo_usuario ) REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_tarjetas
ADD CONSTRAINT tbl_tarjetas_tbl_metodos_pago_fk 
FOREIGN KEY ( metodo_pago ) REFERENCES tbl_metodos_pago ( codigo_metodo_pago );

ALTER TABLE tbl_usuarios
ADD CONSTRAINT tbl_usuarios_tbl_datos_privacidad_fk 
FOREIGN KEY ( datos_priv ) REFERENCES tbl_datos_privacidad ( codigo_datos_priv );

ALTER TABLE tbl_usuarios
ADD CONSTRAINT tbl_usuarios_tbl_direcciones_fk
FOREIGN KEY ( direccion ) REFERENCES tbl_direcciones ( codigo_direccion );

ALTER TABLE tbl_usuarios
ADD CONSTRAINT tbl_usuarios_tbl_planes_fk 
FOREIGN KEY ( plan ) REFERENCES tbl_planes ( codigo_plan );

ALTER TABLE tbl_usuarios
ADD CONSTRAINT tbl_usuarios_tbl_preferencias_fk 
FOREIGN KEY ( preferencia ) REFERENCES tbl_preferencias ( codigo_preferencia );

ALTER TABLE tbl_usuarios
ADD CONSTRAINT tbl_usuarios_tbl_tarjetas_fk 
FOREIGN KEY ( tarjeta ) REFERENCES tbl_tarjetas ( codigo_tarjeta );

ALTER TABLE tbl_versiones_archivo
ADD CONSTRAINT tbl_versiones_archivo_tbl_archivos_fk 
FOREIGN KEY ( codigo_archivo) REFERENCES tbl_archivos ( codigo_archivo );
